import Head from "next/head";
import Image from "next/image";
import JobList from "../components/JobList";

const defaultEndpoint = `https://api.json-generator.com/templates/ZM1r0eic3XEy/data?access_token=${process.env.NEXT_PUBLIC_API_KEY}`;

// const defaultEndpoint = "https://63643eb07b209ece0f4374a5.mockapi.io/jobs";

export async function getStaticProps() {
  const res = await fetch(defaultEndpoint);
  const data = await res.json();

  if (!data) {
    return {
      notFound: true,
    };
  }

  // const data = [...resData, ...resData, ...resData, ...resData, ...resData, ...resData, ...resData];

  return {
    props: { jobs: data },
  };
}

const Home = ({ jobs }) => {
  return (
    <div>
      <Head>
        <title>Kyrylo Lolenko</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <JobList jobs={jobs} />
    </div>
  );
};

export default Home;
